
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtbaxzeuhscpsebwpzcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0YmF4emV1aHNjcHNlYndwemN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NzEyMzYsImV4cCI6MjA1OTQ0NzIzNn0.tdPNYC5gbzmlZn-U4jS82z2i7K-f_PJZF-Zyyk06Q_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storageKey: 'docapp-auth-token',
      detectSessionInUrl: true,
      flowType: 'implicit'
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    },
    global: {
      headers: {
        'x-application-name': 'doctor-appointment-app'
      }
    }
  }
);

// More detailed logging for debugging
export const logSupabaseOperation = async (operation: string, promise: Promise<any>) => {
  try {
    console.log(`Starting Supabase operation: ${operation}`);
    const result = await promise;
    console.log(`Supabase ${operation} result:`, result);
    
    if (result.error) {
      console.error(`Supabase ${operation} error:`, result.error);
    }
    
    return result;
  } catch (err) {
    console.error(`Unexpected error in Supabase ${operation}:`, err);
    throw err;
  }
};

// Test function to verify Supabase connection
export const testSupabaseConnection = async () => {
  try {
    const { data, error } = await supabase.from('doctors').select('*').limit(1);
    if (error) {
      console.error('Supabase connection test failed:', error);
      return { success: false, error };
    }
    console.log('Supabase connection test succeeded:', data);
    return { success: true, data };
  } catch (err) {
    console.error('Unexpected error testing Supabase connection:', err);
    return { success: false, error: err };
  }
};
